name: Build Matrix DOCX

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: with-toc
            input_folder: sample
            output_file: dist/with-toc.docx
            config: sample/defaults.yml
          - name: no-toc
            input_folder: sample

    uses: kyonenya/pandoc-jp-docx/.github/workflows/docx.yml@main
    with:
      name: ${{ matrix.target.name }}
      input_folder: ${{ matrix.target.input_folder }}
      output_file: ${{ matrix.target.output_file }}
      config: ${{ matrix.target.config }}
      shared_ref: main
