name: Build Sample DOCX

on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: write

jobs:
  with-toc:
    uses: kyonenya/pandoc-jp-docx/.github/workflows/docx.yml@dev
    with:
      name: single-with-toc
      input_folder: sample
      output_file: dist/single-with-toc.docx
      config: sample/defaults.yml
      shared_ref: dev

  defaults-only:
    uses: kyonenya/pandoc-jp-docx/.github/workflows/docx.yml@dev
    with:
      name: single-defaults-only
      input_folder: sample
      output_file: dist/single-defaults-only.docx
      shared_ref: dev
