name: Build Sample DOCX

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  no-config:
    uses: kyonenya/pandoc-jp-docx/.github/workflows/docx.yml@dev
    with:
      input_pattern: sample/[0-9]*.md
      output_name: no-config

  with-config:
    uses: kyonenya/pandoc-jp-docx/.github/workflows/docx.yml@dev
    with:
      input_pattern: sample/[0-9]*.md
      output_name: with-config
      defaults: sample/defaults.yml
      pdf: true
    secrets:
      onedrive_client_id: ${{ secrets.ONEDRIVE_CLIENT_ID }}
      onedrive_refresh_token: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
