name: Build DOCX via Pandoc

on:
  workflow_call:
    inputs:
      input_pattern:
        required: true
        type: string
      output_name:
        required: true
        type: string
      defaults:
        required: false
        type: string
        default: ''
      shared_ref:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout shared workflow files
        uses: actions/checkout@v6
        with:
          repository: kyonenya/pandoc-jp-docx
          ref: ${{ inputs.shared_ref }}

      - name: Checkout caller repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: caller

      - name: Convert Markdown to DOCX
        id: pandoc
        uses: docker://pandoc/core:latest
        with:
          entrypoint: /bin/sh
          args: >-
            build.sh
            caller/${{ inputs.input_pattern }}
            caller/dist/${{ inputs.output_name }}.docx
            ${{ inputs.defaults && format('--defaults=caller/{0}', inputs.defaults) || '' }}
            --no-postprocess

      - name: Fix generated file ownership
        run: sudo chown -R "$USER:$USER" caller/dist

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26

      - name: Postprocess DOCX numbering
        run: ./postprocess/numbering.sh "caller/dist/${{ inputs.output_name }}.docx"

      - name: Publish DOCX
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd caller/dist

          git init -b "${{ github.ref_name }}_pandoc-${{ inputs.output_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Publish DOCX: ${{ github.sha }}"

          gh auth setup-git
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git push --force origin HEAD
